title = "COPRRA gitleaks config"

[allowlist]
# تجاهل مجلدات الاعتماديات والملفات غير البرمجية لتقليل الضجيج
paths = [
  '''^vendor/''',
  '''^node_modules/''',
  '''^storage/''',
  '''^tmp/''',
  '''^bootstrap/''',
  '''^build/''',
  '''^dist/''',
  '''^coverage/''',
  '''^\\.cache/''',
  '''^\\.git/''',
  '''^release/''',
  '''^reports/''',
  '''^public/build/''',
  '''^public/storage/''',
  '''^docker/ssl/'''
]

# تجاهل بعض الملفات الكبيرة أو التقارير التي تولّد إنذارات كاذبة
files = [
  '''composer.lock''',
  '''package-lock.json''',
  '''yarn.lock''',
  '''pnpm-lock.yaml''',
  '''npm-shrinkwrap.json''',
  '''trivy-fs.json'''
]

# تجاهل نصوص تجريبية/وهمية شائعة في أمثلة الاختبارات
regexes = [
  '''(?i)dummy|placeholder|example|sample|testkey|testsecret|lorem|ipsum'''
]
