services:
  app:
    build:
      context: .
      dockerfile: dev-docker/Dockerfile
    container_name: coprra-app
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    networks:
      - coprra-net

  nginx:
    image: nginx:stable
    container_name: coprra-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./dev-docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - coprra-net

networks:
  coprra-net:
    driver: bridge
