services:
  app:
    build:
      context: .
      dockerfile: dev-docker/Dockerfile
    container_name: coprra-app
    user: "0:0" # Run php-fpm master as root to allow switching to www-data
    volumes:
      - ./:/var/www/html
      - ./dev-docker/zz-custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
      - ./dev-docker/php.ini:/usr/local/etc/php/conf.d/opcache-dev.ini:ro
      - ./dev-docker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - "9000"
    ports:
      - "5173:5173"
      - "5174:5174"
    networks:
      - coprra-net

  nginx:
    image: nginx:stable
    container_name: coprra-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./dev-docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - coprra-net

networks:
  coprra-net:
    driver: bridge