# Prometheus Configuration for COPRRA
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'coprra-production'
    replica: 'prometheus-1'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files: []

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MySQL exporter (if you add it later)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']

  # Redis exporter (if you add it later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Node exporter (if you add it later)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
