<?php

declare(strict_types=1);

namespace App\Services\AgentFixer;

final class MessageGeneratorService
{
    public function getCommitMessage(string $type): string
    {
        return match ($type) {
            'style' => 'style: Apply automated code style fixes',
            'analysis' => 'refactor: Generate PHPStan baseline',
            default => "fix: Apply automated {$type} fixes"
        };
    }

    public function getPullRequestTitle(string $type): string
    {
        return match ($type) {
            'style' => 'Automated Style Fixes',
            'analysis' => 'Automated Static Analysis Fixes: PHPStan Baseline',
            default => "Automated {$type} Fixes"
        };
    }

    public function getPullRequestBody(string $type): string
    {
        return match ($type) {
            'style' => 'This PR was automatically generated by the AI agent to apply code style fixes found by Laravel Pint.',
            'analysis' => 'This PR was automatically generated by the AI agent to create a PHPStan baseline file for static analysis.',
            default => "This PR was automatically generated by the AI agent to apply {$type} fixes."
        };
    }
}
