services:
  app:
    environment:
      APP_ENV: development
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: coprra
      DB_USERNAME: coprra
      DB_PASSWORD: coprra
      TELESCOPE_ENABLED: "false"
    volumes:
      - .:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
  nginx:
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./dev-docker/nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0
    ports:
      - "127.0.0.1:33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coprra
      MYSQL_USER: coprra
      MYSQL_PASSWORD: coprra
    networks:
      - coprra-net