name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer, cs2pr
          coverage: xdebug
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          npm ci
      - name: Validate composer
        run: composer validate --strict
      - name: Security audits
        run: |
          composer audit --no-interaction || true
          npm audit --audit-level=high || true
      - name: Static analysis
        run: |
          vendor/bin/phpstan analyse --no-progress
          vendor/bin/psalm --no-cache
      - name: Insights
        run: vendor/bin/phpinsights analyse app --no-interaction || true
      - name: Prepare env
        run: cp .env.example .env
      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-text
