name: Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo_mysql, tokenizer, xml, gd, zip
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Cache Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Prepare Laravel directories
        run: |
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/logs
          mkdir -p bootstrap/cache
          chmod -R 777 storage bootstrap/cache

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-ansi --optimize-autoloader --no-dev

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
        env:
          APP_ENV: production
          CACHE_DRIVER: redis
          SESSION_DRIVER: redis

      - name: Run Security Audit
        run: |
          composer audit
          npm audit --audit-level=moderate

      - name: Run Code Quality Checks
        continue-on-error: true
        run: |
          vendor/bin/pint --test --configuration=pint.json || true
          vendor/bin/phpstan analyse --memory-limit=1G --configuration=phpstan.neon
          vendor/bin/psalm --config=psalm.xml || true
          vendor/bin/phpmd app text phpmd.xml

      - name: Run Frontend Quality Checks
        run: |
          npx eslint resources/js --ext .js,.vue,.ts --config=eslint.config.js
          npx stylelint "resources/**/*.{css,scss,vue}" --config=.stylelintrc.json
          npx prettier --check "resources/**/*.{js,css,scss,vue}"

      - name: Run Architecture Analysis
        run: vendor/bin/deptrac analyse --config-file=deptrac.yaml

      - name: Run Mutation Testing
        run: vendor/bin/infection --configuration=infection.json.dist --min-msi=80 --min-covered-msi=80

      - name: Deploy to Production
        run: php scripts/deploy-to-hostinger.php
        env:
          HOSTINGER_DB_HOST: ${{ secrets.HOSTINGER_DB_HOST }}
          HOSTINGER_DB_DATABASE: ${{ secrets.HOSTINGER_DB_DATABASE }}
          HOSTINGER_DB_USERNAME: ${{ secrets.HOSTINGER_DB_USERNAME }}
          HOSTINGER_DB_PASSWORD: ${{ secrets.HOSTINGER_DB_PASSWORD }}
          HOSTINGER_MAIL_HOST: ${{ secrets.HOSTINGER_MAIL_HOST }}
          HOSTINGER_MAIL_USERNAME: ${{ secrets.HOSTINGER_MAIL_USERNAME }}
          HOSTINGER_MAIL_PASSWORD: ${{ secrets.HOSTINGER_MAIL_PASSWORD }}

      - name: Post-deployment Verification
        run: |
          echo "Post-deployment verification completed via deploy script"
          # Additional verification can be added here if needed
