name: Performance Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: "0 4 * * *" # Run daily at 4 AM
  workflow_dispatch:

jobs:
  performance-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo_mysql, tokenizer, xml, gd, zip, xdebug
          coverage: xdebug
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Cache Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Prepare Laravel directories
        run: |
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/logs
          mkdir -p bootstrap/cache
          chmod -R 777 storage bootstrap/cache

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-ansi --optimize-autoloader

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
        env:
          APP_ENV: testing
          CACHE_DRIVER: array
          SESSION_DRIVER: array

      - name: Setup Database
        run: |
          php artisan migrate --force
          php artisan db:seed || true

      - name: Run Performance Tests
        run: vendor/bin/phpunit tests/Performance/ --coverage-clover=coverage-performance.xml --coverage-html=coverage-performance --configuration=phpunit.xml

      - name: Run Load Tests
        run: vendor/bin/phpunit tests/Performance/LoadTestingTest.php --coverage-clover=coverage-load.xml --coverage-html=coverage-load --configuration=phpunit.xml

      - name: Run Stress Tests
        run: vendor/bin/phpunit tests/Performance/ --coverage-clover=coverage-stress.xml --coverage-html=coverage-stress --configuration=phpunit.xml

      - name: Run Memory Tests
        run: vendor/bin/phpunit tests/Performance/MemoryUsageTest.php --coverage-clover=coverage-memory.xml --coverage-html=coverage-memory --configuration=phpunit.xml

      - name: Run Database Performance Tests
        run: vendor/bin/phpunit tests/Performance/DatabasePerformanceTest.php --coverage-clover=coverage-database.xml --coverage-html=coverage-database --configuration=phpunit.xml

      - name: Run API Performance Tests
        run: vendor/bin/phpunit tests/Performance/ApiResponseTimeTest.php --coverage-clover=coverage-api.xml --coverage-html=coverage-api --configuration=phpunit.xml

      - name: Upload Performance Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-results
          path: |
            coverage-performance.xml
            coverage-performance/
            coverage-load.xml
            coverage-load/
            coverage-stress.xml
            coverage-stress/
            coverage-memory.xml
            coverage-memory/
            coverage-database.xml
            coverage-database/
            coverage-api.xml
            coverage-api/
          retention-days: 7
